modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="passablefoliage"
version="${file.jarVersion}"
displayName="Passable Foliage"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/passable-foliage"
description="Remove collision from leaves"

[[dependencies.passablefoliage]]
    modId="kiwi"
    mandatory=true
    versionRange="[11,)"
    ordering="NONE"
    side="BOTH"

[modproperties.passablefoliage]
    catalogueItemIcon="minecraft:oak_leaves" #Support for Catalogue mod
